Add instructions for working with Collections locally
hypermodeinc/docs pull request #58
Opened 2024-11-01 18:55 UTC by johnymontana

2024-11-03 16:27 UTC, johnymontana commented
okie this is ready for a review now please :-)

2024-11-04 00:57 UTC, ryanfoxtyler requested changes

2024-11-04 00:57 UTC, ryanfoxtyler commented on modus/search.mdx
> +
```suggestion
<Note>
The dependency on PostgreSQL is temporary and we're working to replace it with ModusDB, an embeddable multi-model database, in an upcoming release.
</Note>
```

2024-11-04 03:15 UTC, johnymontana commented on modus/search.mdx
> +
updated

2024-11-04 11:43 UTC, ryanfoxtyler approved these changes

2024-11-04 11:43 UTC, merged